### ISSUE TITLE
ldapjs doesn't builds with node v0.6.1

### ISSUE THREAD

**Issue by bbigras** [mcavage/node-ldapjs#34]
I just upgraded to node v0.6.1 and I can't build ldapjs. I'm using Ubuntu packages from https://launchpad.net/~chris-lea/+archive/node.js/

```
bbigras@ubuntu:/home/bbigras/test/node_modules/ldapjs$ make
npm_config_tar=tar npm install --dev

> buffertools@1.0.5 preinstall /home/bbigras/test/node_modules/ldapjs/node_modules/buffertools
> ./build-wrapper


> dtrace-provider@0.0.3 install /home/bbigras/test/node_modules/ldapjs/node_modules/dtrace-provider
> node-waf configure build

Setting srcdir to                        : /home/bbigras/test/node_modules/ldapjs/node_modules/buffertools
Setting blddir to                        : /home/bbigras/test/node_modules/ldapjs/node_modules/buffertools/build
Checking for program g++ or c++          : /usr/bin/g++
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : not found
Checking for node prefix                 : ok /usr
'configure' finished successfully (0.288s)
Waf: Entering directory `/home/bbigras/test/node_modules/ldapjs/node_modules/buffertools/build'
[1/2] cxx: buffertools.cc -> build/Release/buffertools_1.o
Checking for program g++ or c++          : /usr/bin/g++
../buffertools.cc:1:16: error: v8.h: No such file or directory
../buffertools.cc:2:18: error: node.h: No such file or directory
../buffertools.cc:3:25: error: node_buffer.h: No such file or directory
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : not found
Checking for node prefix                 : ok /usr
'configure' finished successfully (0.308s)
Waf: Entering directory `/home/bbigras/test/node_modules/ldapjs/node_modules/dtrace-provider/build'
[1/3] cxx: dtrace_provider.cc -> build/Release/dtrace_provider_1.o
[2/3] cxx: dtrace_dof.cc -> build/Release/dtrace_dof_1.o
In file included from ../dtrace_dof.cc:1:
../dtrace_provider.h:1:18: error: node.h: No such file or directory
../dtrace_provider.h:2:30: error: node_object_wrap.h: No such file or directory
../dtrace_provider.h:3:16: error: v8.h: No such file or directory
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:1:18: error: node.h: No such file or directory
../dtrace_provider.h:2:30: error: node_object_wrap.h: No such file or directory
../dtrace_provider.h:3:16: error: v8.h: No such file or directory
Waf: Leaving directory `/home/bbigras/test/node_modules/ldapjs/node_modules/dtrace-provider/build'
Build failed:
 -> task failed (err #1):
        {task: cxx dtrace_dof.cc -> dtrace_dof_1.o}
 -> task failed (err #1):
        {task: cxx dtrace_provider.cc -> dtrace_provider_1.o}
npm ERR! error installing dtrace-provider@0.0.3 Error: dtrace-provider@0.0.3 install: `node-waf configure build`
npm ERR! error installing dtrace-provider@0.0.3 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing dtrace-provider@0.0.3     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing dtrace-provider@0.0.3     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing dtrace-provider@0.0.3     at maybeExit (child_process.js:359:16)
npm ERR! error installing dtrace-provider@0.0.3     at Process.onexit (child_process.js:395:5)
npm ERR! dtrace-provider@0.0.3 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.0.3 install script.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 2.6.32-35-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "--dev"
npm ERR! cwd /home/bbigras/test/node_modules/ldapjs
npm ERR! node -v v0.6.1
npm ERR! npm -v 1.0.105
npm ERR! code ELIFECYCLE
../buffertools.cc:12: error: ‘v8’ is not a namespace-name
../buffertools.cc:12: error: expected namespace-name before ‘;’ token
../buffertools.cc:13: error: ‘node’ is not a namespace-name
../buffertools.cc:13: error: expected namespace-name before ‘;’ token
../buffertools.cc:19: error: ISO C++ forbids declaration of ‘Handle’ with no type
../buffertools.cc:19: error: expected ‘;’ before ‘<’ token
../buffertools.cc:21: error: ISO C++ forbids declaration of ‘Handle’ with no type
../buffertools.cc:21: error: expected ‘;’ before ‘<’ token
../buffertools.cc:342: error: expected ‘;’ at end of input
../buffertools.cc:342: error: expected ‘}’ at end of input
../buffertools.cc:342: error: expected unqualified-id at end of input
../buffertools.cc:342: error: expected ‘}’ at end of input
Waf: Leaving directory `/home/bbigras/test/node_modules/ldapjs/node_modules/buffertools/build'
Build failed:  -> task failed (err #1):
        {task: cxx buffertools.cc -> buffertools_1.o}
npm ERR! error installing buffertools@1.0.5 Error: buffertools@1.0.5 preinstall: `./build-wrapper`
npm ERR! error installing buffertools@1.0.5 `sh "-c" "./build-wrapper"` failed with 1
npm ERR! error installing buffertools@1.0.5     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing buffertools@1.0.5     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing buffertools@1.0.5     at maybeExit (child_process.js:359:16)
npm ERR! error installing buffertools@1.0.5     at Process.onexit (child_process.js:395:5)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bbigras/test/node_modules/ldapjs/npm-debug.log
npm not ok
make: *** [node_modules/.ldapjs.npm.installed] Error 1
```
